import { useApi, ErrorBox, Loading } from './ui.jsx';
import { Link } from './router.jsx';
import { pct, num } from './api.js';
const M={company:{eyebrow:'PARTNER HOME',title:'社会の知見を、\n次の世代の学びへ。',body:'仕事の現場にある問いが、生徒の探究のはじまりになる。',cta:'カリキュラムをつくる',path:'/curriculum'},teacher:{eyebrow:'TEACHER HOME',title:'今日の学びを、\n未来の選択につなぐ。',body:'企業のリアルな課題を教材に、一人ひとりの気づきに伴走しましょう。',cta:'授業を確認する',path:'/lessons'},student:{eyebrow:'MY LEARNING',title:'今日の「気になる」から、\nはじめよう。',body:'社会を知ることは、自分を知ること。小さな発見を記録していこう。',cta:'今日の授業へ',path:'/lessons'}};
export default function Overview({user}){
 const role=user.role,m=M[role],info=useApi(role==='company'?'/company/report':role==='teacher'?'/teacher/classes':'/student/home'),lessons=useApi(role==='company'?'/learning/company-report':'/learning/lessons');
 if(info.loading)return <Loading/>;if(info.error)return <ErrorBox error={info.error} onRetry={info.reload}/>;const d=info.data;
 const stats=role==='company'?[['教材が届いた学校',d.totals.schoolsReached,'校'],['テーマの閲覧',d.totals.views,'件'],['生徒の関心率',pct(d.totals.interestRate),''],['採用された教材',lessons.data?.curricula.reduce((s,c)=>s+c.adoptionCount,0)??'—','件']]:role==='teacher'?[['担当クラス',d.classes.length,'クラス'],['担当する生徒',d.classes.reduce((s,c)=>s+c.students,0),'人'],['準備した授業',lessons.data?.lessons.length??'—','件'],['授業後アンケート',d.pendingLessonSurveys,'件 未回答']]:[['今週の振り返り',d.stats.submittedThisWeek,'回'],['積み重ねた記録',d.stats.total,'件'],['届いているテーマ',d.themes.length,'件'],['参加する授業',lessons.data?.lessons.length??'—','件']];
 return <div className="stack overview"><div className="page-heading"><div><span className="eyebrow">{m.eyebrow}</span><h1>{role==='company'?user.company?.name:role==='teacher'?'こんにちは、先生。':'こんにちは。今日も一歩、未来へ。'}</h1><p className="muted small">{role==='company'?'企業パートナーの活動ダッシュボード':role==='teacher'?`${user.school?.name} · 担当クラスの学びを見渡す`:`${user.class?.grade}年${user.class?.name}組 ${user.attendanceNo}番 · あなたの学びのワークスペース`}</p></div><span className="date-chip">{new Date().toLocaleDateString('ja-JP',{month:'long',day:'numeric',weekday:'short'})}</span></div>
 <section className="overview-hero"><div><span className="eyebrow">LEARNING CONNECTS OUR FUTURE</span><h2>{m.title}</h2><p>{m.body}</p><Link className="btn primary" to={m.path}>{m.cta}　→</Link></div><figure><img src="/images/learning-scene.png" alt="企業の技術者と生徒が学ぶ架空の授業シーン"/><figcaption>社会とつながる学び / AI生成イメージ</figcaption></figure></section>
 <div className="stats-grid">{stats.map(([label,val,unit],i)=><div className="stat-tile" key={label}><div className="spread"><span>{label}</span><span className={`stat-icon stat-${i}`}>{['◈','▤','↗','◎'][i]}</span></div><b>{val}<small>{unit}</small></b></div>)}</div>
 <div className="dashboard-grid"><section className="panel"><div className="spread"><div><span className="eyebrow">{role==='company'?'YOUR IMPACT':'NEXT CLASS'}</span><h2>{role==='company'?'教材が生んだ、学びの変化':'授業の予定と進行'}</h2></div><Link to={role==='company'?'/curriculum':'/lessons'} className="text-link">すべて見る →</Link></div><ErrorBox error={lessons.error}/>{role==='company'?<><p className="small muted">理解度の前後比較は自己評価です。5人未満は集計を表示しません。</p>{lessons.data?.curricula.slice(0,4).map(c=><article className="impact-row" key={c.curriculumId}><div><b>{c.title}</b><small>教員採用 {c.adoptionCount}件 · 授業 {c.lessonCount}件</small></div><div className="impact-score">{c.suppressed?'集計待ち':`${num(c.beforeAverage)} → ${num(c.afterAverage)}`}<small>理解度 / 5</small></div></article>)}</>:(lessons.data?.lessons.length?lessons.data.lessons.slice(0,4).map(l=><Link to="/lessons" className="class-preview" key={l.id}><span className="lesson-symbol">▤</span><div><small>{l.className} · {l.duration}分</small><b>{l.title}</b></div><span className={`badge ${l.status==='active'?'pen':''}`}>{({active:'授業中',planned:'開始前',completed:'終了'})[l.status]}</span></Link>):<p className="muted">まだ授業がありません。{role==='teacher'?'教材ライブラリから授業を準備しましょう。':'先生からの配信をお待ちください。'}</p>)}</section><section className="panel quick-panel"><span className="eyebrow">QUICK ACCESS</span><h2>次のアクション</h2>{(role==='company'?[['01','知見を教材にする','入力・編集して学校へ提供','/curriculum'],['02','生徒の反応を知る','関心と匿名の声を確認','/reports'],['03','素材を届ける','参考資料やリンクを共有','/materials']]:role==='teacher'?[['01','授業を準備する','教材の採用・編集・最終承認','/curriculum'],['02','生徒の記録を見る','提出状況・コメント・要確認','/classes'],['03','授業を振り返る','授業後アンケートに回答','/lesson-surveys']]:[['01','今日の手帳を記録','撮影・確認・提出','/capture'],['02','気になるテーマを探す','社会のリアルな問いに出会う','/themes'],['03','わたしの未来を見る','関心・次の行動・mirAI共有','/career']]).map(([n,title,desc,path])=><Link className="quick-link" key={n} to={path}><span>{n}</span><div><b>{title}</b><small>{desc}</small></div><em>↗</em></Link>)}</section></div>
 <section className="journey-banner"><div><span className="eyebrow">THE LEARNING CYCLE</span><h3>社会と出会い、自分の可能性をひらく。</h3></div><div><span>企業の知見</span><b>→</b><span>探究する授業</span><b>→</b><span>自分の振り返り</span><b>→</b><span>未来への一歩</span></div></section></div>;
}
